export { default as img0 } from "./00-jose-aparecido-nunes.webp"
export { default as img1 } from "./01-manoel-gomes-satos.webp"
export { default as img2 } from "./02-maurilio-calvo-filho.webp"
export { default as img3 } from "./03-rita-cassia-santos-correa.webp"
export { default as img4 } from "./04-sidnei-moises-ferreira.webp"
