export { default as img1 } from "./logo-alfa.png"
export { default as img2 } from "./logo-emercor.webp"
export { default as img3 } from "./logo-policlin.webp"
export { default as img4 } from "./logo-santa-casa.webp"
export { default as img5 } from "./logo-unimed.webp"
